frontend:
  - "src/**"
  - "index.html"
  - "vite.config.ts"
  - "package.json"
  - "tsconfig.json"

backend:
  - "backend/**"

documentation:
  - "*.md"
  - "docs/**"
  - "INSTALL.txt"

infrastructure:
  - "Dockerfile"
  - "docker-compose*.yml"
  - "docker-entrypoint.sh"
  - "k8s/**"

"ci/cd":
  - ".github/**"

dependencies:
  - "package.json"
  - "package-lock.json"
  - "backend/requirements.txt"
